version: 0.2
os: linux
files:
  - source: /
    destination: /home/ubuntu/app

hooks:
  BeforeInstall:
    - location: scripts/stop_old_container.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/start_new_container.sh
      timeout: 300
      runas: ubuntu
  ValidateService:
    - location: scripts/validate.sh
      timeout: 300
      runas: ubuntu
